spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.anljpqtmazhnyjegddmx
spring.datasource.password=Bits@1508199