spring.application.name=Microservice-for-MPL

spring.datasource.username=postgres
spring.datasource.password=azad
spring.datasource.url=jdbc:postgresql://localhost:5432/mpl
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true


spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml